In [1]:
import pandas as pd
import numpy as np

In [2]:
pp_base=pd.read_csv('Absenteeism_project_preprocessed_file.csv')

In [3]:
mldf=pp_base.copy()
mldf.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

#### Classifying absenteeism into 'Excessively absent'(more than 3 hrs) and 'Moderately absent' (less than or equal to 3 hrs)

In [4]:
#Finding median for Absenteeism in Hours
mldf['Absenteeism Time in Hours'].median()

#Take value '1' for employees absent for more than 3 hrs and '0' for less than or equal to 3 hrs

3.0

In [5]:
targets=np.where(mldf['Absenteeism Time in Hours']>3,1,0)

# targets=<numpy_function>.where(if the values of 'Absenteeism in hours' is greater than 3,<store as 1>,<else store 0>)

In [6]:
#Adding the new values ('0' & '1') to Absenteeism column
mldf['Excessive Absenteeism']=targets
mldf.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
targets.sum()/targets.shape[0]
#around 46% of the targets are 1's

0.45571428571428574

In [8]:
#Dropping 'Absenteeism in Hours'
data_with_targets=mldf.drop(['Absenteeism Time in Hours'],axis=1)
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [9]:
#Selecting specific rows and columns
mldf.iloc[:6,:14]
#mlfd.iloc['row','column']
#mldf.iloc[':,0:14'] ':' means all rows, 0:14 means select columns 0 to 14
#mldf.iloc[4:8,5:10] '4:8' means rows 4 to 8, '5:10' means columns 5 to 10

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   
5        0        0        0        1           10                2   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1  
5               31          0         0     0

In [10]:
mldf.iloc[:6,:-1]
#. -1 means display all other columns except last column
#  -2  "           "          "        "     last 2 columns and so on 

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   
5        0        0        0        1           10                2   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2

In [11]:
unscaled_inputs=data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

### Standardising the data

In [12]:
from sklearn.preprocessing import StandardScaler 

#### Checkpoint 1

In [13]:
mldf1=unscaled_inputs.copy()

In [14]:
mldf1.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [15]:
nodum=mldf1.copy()

nodum.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

In [16]:
cols_to_omit=['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Education','Month value', 'Distance to Work' ]

In [17]:
cols_to_scale=[x for x in nodum.columns.values if x not in cols_to_omit]

In [18]:
absenteeism_scaler=StandardScaler(cols_to_scale)
#Creating StandardScaler object

In [19]:
absenteeism_scaler.fit(nodum)
#this will calculate and store the mean & the standard deviation
#Standardisation info is contained in absenteeism_scaler

StandardScaler(copy=['Day of the week', 'Transportation Expense', 'Age',
                     'Daily Work Load Average', 'Body Mass Index', 'Children',
                     'Pets'],
               with_mean=True, with_std=True)

In [20]:
#Applying the above scaling mechanism (transform)
scaled_inputs=absenteeism_scaler.transform(nodum)
# (.transform does the actual scaling)

In [21]:
nodum.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

#### Splitting the data into train, test and shuffle

In [22]:
#Import module
from sklearn.model_selection import train_test_split

In [23]:
#Split
train_test_split(scaled_inputs,targets)

#syntax 
# sklearn.mode_selection.train_test_split(inputs, targets, train_size*, shuffle=True**, random_state***)
# * train_size - value b/w 0 and 1 - denotes percentage of data to be trained
# ** shuffle - by default - True
# *** random_state - takes integer value - shuffles in random way

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
          0.88046927, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [24]:
#Assigning variables to above arrays
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets)

In [25]:
#View shape
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(525, 14) (525,)
(175, 14) (175,)


In [26]:
#Assigning 80%-20% for training-testing
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [27]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 14) (560,)
(140, 14) (140,)


#### Training the model and testing accuracy

In [28]:
#import modules
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
#Training the model
#Creating new variable which should be a logistic regression object
reg=LogisticRegression()

In [30]:
#Fitting the regression
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
reg.score(x_train,y_train)

0.7803571428571429

In [32]:
#Manual check
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_outputs==y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum((model_outputs==y_train))

437

In [36]:
model_outputs.shape[0]

560

In [37]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7803571428571429

In [38]:
reg.intercept_

array([-0.21150898])

In [39]:
reg.coef_

array([[ 2.07192269,  0.33075027,  1.56390046,  1.31283678,  0.02577323,
        -0.08622837,  0.72326969, -0.06149037, -0.20628304, -0.02865604,
         0.3259002 , -0.16141702,  0.38153429, -0.32129837]])

In [40]:
feature_name=nodum.columns.values

In [41]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table

Feature name
0                   Reason1
1                   Reason2
2                   Reason3
3                   Reason4
4               Month value
5           Day of the week
6    Transportation Expense
7          Distance to Work
8                       Age
9   Daily Work Load Average
10          Body Mass Index
11                Education
12                 Children
13                     Pets

In [42]:
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                   Reason1     2.071923
1                   Reason2     0.330750
2                   Reason3     1.563900
3                   Reason4     1.312837
4               Month value     0.025773
5           Day of the week    -0.086228
6    Transportation Expense     0.723270
7          Distance to Work    -0.061490
8                       Age    -0.206283
9   Daily Work Load Average    -0.028656
10          Body Mass Index     0.325900
11                Education    -0.161417
12                 Children     0.381534
13                     Pets    -0.321298

In [43]:
#Adding intercept on top of the df
summary_table.index=summary_table.index+1 #increases all indices by 1

In [44]:
summary_table.loc[0]=['Intercept', reg.intercept_[0]]

In [45]:
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.211509
1                   Reason1     2.071923
2                   Reason2     0.330750
3                   Reason3     1.563900
4                   Reason4     1.312837
5               Month value     0.025773
6           Day of the week    -0.086228
7    Transportation Expense     0.723270
8          Distance to Work    -0.061490
9                       Age    -0.206283
10  Daily Work Load Average    -0.028656
11          Body Mass Index     0.325900
12                Education    -0.161417
13                 Children     0.381534
14                     Pets    -0.321298

In [46]:
#Getting exponentials of all coefficients
summary_table['Odds ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds ratio
0                 Intercept    -0.211509    0.809362
1                   Reason1     2.071923    7.940075
2                   Reason2     0.330750    1.392012
3                   Reason3     1.563900    4.777419
4                   Reason4     1.312837    3.716702
5               Month value     0.025773    1.026108
6           Day of the week    -0.086228    0.917385
7    Transportation Expense     0.723270    2.061162
8          Distance to Work    -0.061490    0.940362
9                       Age    -0.206283    0.813603
10  Daily Work Load Average    -0.028656    0.971751
11          Body Mass Index     0.325900    1.385277
12                Education    -0.161417    0.850937
13                 Children     0.381534    1.464530
14                     Pets    -0.321298    0.725207

In [47]:
summary_table.sort_values('Odds ratio',ascending=False)

Feature name  Coefficient  Odds ratio
1                   Reason1     2.071923    7.940075
3                   Reason3     1.563900    4.777419
4                   Reason4     1.312837    3.716702
7    Transportation Expense     0.723270    2.061162
13                 Children     0.381534    1.464530
2                   Reason2     0.330750    1.392012
11          Body Mass Index     0.325900    1.385277
5               Month value     0.025773    1.026108
10  Daily Work Load Average    -0.028656    0.971751
8          Distance to Work    -0.061490    0.940362
6           Day of the week    -0.086228    0.917385
12                Education    -0.161417    0.850937
9                       Age    -0.206283    0.813603
0                 Intercept    -0.211509    0.809362
14                     Pets    -0.321298    0.725207

A feature is not particular important:
- if co-efficient is around 0
- if odds ratio is around 1

In [48]:
reg.score(x_test,y_test)

0.7285714285714285

In [49]:
#Predicting the probability of getting output as 0 or 1
predicted_proba=reg.predict_proba(x_test)
predicted_proba
# in the below output, left side values are the probability of getting '0' 
# & right-side values are the probability of getting '1'

array([[0.76491084, 0.23508916],
       [0.61192048, 0.38807952],
       [0.40784145, 0.59215855],
       [0.78559655, 0.21440345],
       [0.06083149, 0.93916851],
       [0.26784831, 0.73215169],
       [0.28605183, 0.71394817],
       [0.06690094, 0.93309906],
       [0.75855461, 0.24144539],
       [0.76534143, 0.23465857],
       [0.47352576, 0.52647424],
       [0.13556274, 0.86443726],
       [0.04167223, 0.95832777],
       [0.69574064, 0.30425936],
       [0.20618035, 0.79381965],
       [0.47712826, 0.52287174],
       [0.49329241, 0.50670759],
       [0.53885687, 0.46114313],
       [0.37820057, 0.62179943],
       [0.02921447, 0.97078553],
       [0.73386668, 0.26613332],
       [0.77723093, 0.22276907],
       [0.42576557, 0.57423443],
       [0.44224601, 0.55775399],
       [0.15267975, 0.84732025],
       [0.76004303, 0.23995697],
       [0.4561684 , 0.5438316 ],
       [0.89844351, 0.10155649],
       [0.16327355, 0.83672645],
       [0.76863503, 0.23136497],
       [0.

In [50]:
#Taking out probability of '1' values only
predicted_proba[:,1]

array([0.23508916, 0.38807952, 0.59215855, 0.21440345, 0.93916851,
       0.73215169, 0.71394817, 0.93309906, 0.24144539, 0.23465857,
       0.52647424, 0.86443726, 0.95832777, 0.30425936, 0.79381965,
       0.52287174, 0.50670759, 0.46114313, 0.62179943, 0.97078553,
       0.26613332, 0.22276907, 0.57423443, 0.55775399, 0.84732025,
       0.23995697, 0.5438316 , 0.10155649, 0.83672645, 0.23136497,
       0.41392386, 0.7416756 , 0.70043063, 0.52911294, 0.22276907,
       0.61590946, 0.2580173 , 0.8321945 , 0.47464544, 0.60652695,
       0.24222774, 0.4168497 , 0.23492313, 0.09791751, 0.82736464,
       0.73250409, 0.76203169, 0.24094288, 0.27200606, 0.20109549,
       0.49863934, 0.07002973, 0.70471341, 0.26201976, 0.86836152,
       0.44109179, 0.95232533, 0.29229644, 0.07773983, 0.0762938 ,
       0.74426178, 0.67997897, 0.28734734, 0.85872611, 0.23886725,
       0.2371924 , 0.01163608, 0.24507887, 0.84424612, 0.31157491,
       0.24414853, 0.07811631, 0.92228586, 0.46681116, 0.65161

In [51]:
#Saving the model
import pickle

In [52]:
#Pickling the reg model
with open('absenteeism_project_model','wb') as file:
    pickle.dump(reg,file)

In [53]:
#Pickling the scaler
with open('absenteeism_project_scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)